clc;
clear all;
format compact

ImOrgData=double(imread('origin\building.tif'));
%% Prewitt
GradX=[-1 -1 -1;0 0 0;1 1 1];
GradY=[-1 0 1;-1 0 1;-1 0 1];
[m,n]=size(ImOrgData);
GradPre=EdgeCom(ImOrgData,GradX,GradY);
EdgePre=true(m,n);
EdgePre1 = EdgePre;
EdgePre2 = EdgePre;
EdgePre3 = EdgePre;
TH1 = 100; TH2 = 150; TH3 = 180;
EdgePre1(GradPre<TH1)=0;
EdgePre2(GradPre<TH2)=0;
EdgePre3(GradPre<TH3)=0;
figure(1);
set(gcf,'Position',get(0,'ScreenSize'),'Name','Prewitt算子');
subplot(2, 2, 1);imshow(uint8(ImOrgData));title('a 原图');
subplot(2, 2, 2);imshow(EdgePre1);title('b Prewitt算子,threshold=100');
subplot(2, 2, 3);imshow(EdgePre2);title('c Prewitt算子,threshold=150');
subplot(2, 2, 4);imshow(EdgePre3);title('d Prewitt算子,threshold=180');
%% Sobel 
GradX=[-1 -2 -1;0 0 0;1 2 1];
GradY=[-1 0 1;-2 0 2;-1 0 1];
[m,n]=size(ImOrgData);
GradSob=EdgeCom(ImOrgData,GradX,GradY);
EdgeSob=true(m,n);
EdgeSob1 = EdgeSob;
EdgeSob2 = EdgeSob;
EdgeSob3 = EdgeSob;
TH1 = 180; TH2 = 200; TH3 = 250;
EdgeSob1(GradSob<TH1)=0;
EdgeSob2(GradSob<TH2)=0;
EdgeSob3(GradSob<TH3)=0;
figure(2);
set(gcf,'Position',get(0,'ScreenSize'),'Name','Sobel算子');
subplot(2, 2, 1);imshow(uint8(ImOrgData));title('a 原图');
subplot(2, 2, 2);imshow(EdgeSob1);title('b Sobel算子,threshold=180');
subplot(2, 2, 3);imshow(EdgeSob2);title('c Sobel算子,threshold=200');
subplot(2, 2, 4);imshow(EdgeSob3);title('d Sobel算子,threshold=250');
%% Roberts
GradX=[-1 0;0 1];
GradY=[0 -1;1 0];
[m,n]=size(ImOrgData);
GradRob=EdgeCom2(ImOrgData,GradX,GradY);
EdgeRob=true(m,n);
EdgeRob1 = EdgeRob;
EdgeRob2 = EdgeRob;
EdgeRob3 = EdgeRob;
TH1 = 40; TH2 = 50; TH3 = 60;
EdgeRob1(GradRob<TH1)=0;
EdgeRob2(GradRob<TH2)=0;
EdgeRob3(GradRob<TH3)=0;
figure(3);
set(gcf,'Position',get(0,'ScreenSize'),'Name','Roberts算子');
subplot(2, 2, 1);imshow(uint8(ImOrgData));title('a 原图');
subplot(2, 2, 2);imshow(EdgeRob1);title('b Roberts算子,threshold=40');
subplot(2, 2, 3);imshow(EdgeRob2);title('c Roberts算子,threshold=50');
subplot(2, 2, 4);imshow(EdgeRob3);title('d Roberts算子,threshold=60');
%% MH
GradX=[0 0 -1 0 0;0 -1 -2 -1 0;-1 -2 16 -2 -1;0 -1 -2 -1 0;0 0 -1 0 0];
[m,n]=size(ImOrgData);
mh=EdgeCom3(ImOrgData,GradX);
EdgeMH=false(m,n);
EdgeMH1 = EdgeMH;
EdgeMH2 = EdgeMH;
EdgeMH3 = EdgeMH;
TH1 = 120; TH2 = 220; TH3 = 300; 
EdgeMH1(abs(mh)>TH1)=1;
EdgeMH2(abs(mh)>TH2)=1;
EdgeMH3(abs(mh)>TH3)=1;
figure(4);
set(gcf,'Position',get(0,'ScreenSize'),'Name','MH');
subplot(2, 2, 1);imshow(uint8(ImOrgData));title('a 原图');
subplot(2, 2, 2);imshow(EdgeMH1);title('b MH,threshold=120');
subplot(2, 2, 3);imshow(EdgeMH2);title('c MH,threshold=220');
subplot(2, 2, 4);imshow(EdgeMH3);title('d MH,threshold=320');
%% Canny
figure(5);
set(gcf,'Position',get(0,'ScreenSize'),'Name','Canny算子');
CnnData=Canny(ImOrgData,50,100);
subplot(1,2,1);imshow(uint8(ImOrgData));title('a 原图');
subplot(1,2,2);imshow(CnnData);title('b Canny算子');
%% Otsu
ImOrgData2 = imread('origin\polymersomes.tif');
[m,n] = size(ImOrgData2);
a = otsu_value(ImOrgData2);
bIm=false(m,n);
bIm(ImOrgData2>a)=1;
bIm2=false(m,n);
bIm2(ImOrgData2>170)=1;
figure(6);
set(gcf,'Position',get(0,'ScreenSize'),'Name','Otsu');
subplot(2,2,1);imshow(ImOrgData2);title('a 原图');
subplot(2,2,2);imshow(bIm),title('b Otsu,threshold = 175');
subplot(2,2,3);imhist(ImOrgData2);title('c 原图直方');
subplot(2,2,4);imshow(bIm2);title('d global,threshold = 170');
